---
title: "2026-04-26_hw03"
author: "Chris"
date: "2026-04-26"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: cosmo
    css: style.css
---

The project is on GitHub: https://github.com/ChrisW12372/2026-04-26_p8160-hw03.git

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(bootstrap)
library(MASS)
library(boot)
library(glmnet)
library(tidymodels)

set.seed(202604)
```


# Problem 1

```{r}
data("law")
```

## Part I

```{r}
r_hat_q1 <- cor(law$LSAT, law$GPA)
r_hat_q1
```


```{r}
z_hat_q1 <- 0.5 * log((1 + r_hat_q1) / (1 - r_hat_q1))
z_hat_q1
```


```{r}
n <- nrow(law)
se_z <- 1 / sqrt(n - 3)

# 95% CI on z scale
z_lower <- z_hat_q1 - qnorm(0.975) * se_z
z_upper <- z_hat_q1 + qnorm(0.975) * se_z

# back-transform to correlation scale
ci_rho <- tanh(c(z_lower, z_upper))
```


```{r}
r_hat_q1
z_hat_q1
se_z
ci_rho
```


## Part II

### Bootstrap

```{r}
set.seed(202604)

B <- 1000
r_star <- numeric(B)

for(b in 1:B){
  idx <- sample(1:n, size = n, replace = TRUE)
  law_star <- law[idx, ]
  
  r_star[b] <- cor(law_star$LSAT, law_star$GPA)
}

se_B <- sd(r_star)
se_B
```


### Confidence Interval

```{r}
set.seed(202604)
alpha <- 0.05
z_crit <- qnorm(1 - alpha / 2)

# a) standard normal bootstrap CI
ci_normal_boot <- c(
  r_hat_q1 - z_crit * se_B,
  r_hat_q1 + z_crit * se_B
)

# b) corrected percentile CI
q_025 <- quantile(r_star, probs = 0.025)
q_975 <- quantile(r_star, probs = 0.975)

ci_corrected_percentile <- c(
  2 * r_hat_q1 - q_975,
  2 * r_hat_q1 - q_025
)

# c) percentile CI
ci_percentile <- c(
  q_025,
  q_975
)

ci_normal_boot
ci_corrected_percentile
ci_percentile
```


## Part III

```{r}
r_hat <- 0.7763745
rho_pop <- 0.776

ci_table <- data.frame(
  Method = c(
    "Fisher z normal approximation",
    "Standard normal bootstrap",
    "Corrected percentile bootstrap",
    "Percentile bootstrap"
  ),
  Lower = c(0.4385108, 0.5107711, 0.5935482, 0.4528802),
  Upper = c(0.9219648, 1.0419778, 1.0998688, 0.9592008)
)

ci_table$Contains_rho_pop <- with(ci_table, Lower <= rho_pop & Upper >= rho_pop)

ci_table$Left_distance <- r_hat - ci_table$Lower
ci_table$Right_distance <- ci_table$Upper - r_hat

ci_table$Symmetric_about_r_hat <- abs(ci_table$Left_distance - ci_table$Right_distance) < 0.01

ci_table
```


# Problem 2

## Part I

```{r}
blue <- c(4,69,87,35,39,79,31,79,65,95,68,
          62,70,80,84,79,66,75,59,77,36,86,
          39,85,74,72,69,85,85,72)

red <- c(62,80,82,83,0,81,28,69,48,90,63,
         77,0,55,83,85,54,72,58,68,88,83,78,
         30,58,45,78,64,87,65)

acui <- data.frame(
  str = c(rep(0, 20), rep(1, 10)),
  red = red,
  blue = blue
)

# paired part
d_paired <- mean(acui$blue[acui$str == 0] - acui$red[acui$str == 0])

# two-sample part
d_twosample <- mean(acui$blue[acui$str == 1]) -
  mean(acui$red[acui$str == 1])

# combined estimator
delta_hat <- (20 / 30) * d_paired + (10 / 30) * d_twosample

d_paired
d_twosample
delta_hat
```


## Part II

```{r}
paired <- acui[acui$str == 0, ]
single <- acui[acui$str == 1, ]

delta_paired <- mean(paired$blue - paired$red)
delta_single <- mean(single$blue) - mean(single$red)

```


```{r}
set.seed(202604)

B <- 1000

n_paired <- nrow(paired)
n_single <- nrow(single)

delta_star <- numeric(B)

for (b in 1:B) {
  # paired part
  idx_p <- sample(1:n_paired, size = n_paired, replace = TRUE)
  paired_star <- paired[idx_p, ]
  
  delta_paired_star <- mean(paired_star$blue - paired_star$red)
  
  # single-eye part
  blue_single_star <- sample(single$blue, size = n_single, replace = TRUE)
  red_single_star  <- sample(single$red,  size = n_single, replace = TRUE)
  
  delta_single_star <- mean(blue_single_star) - mean(red_single_star)
  
  # combined estimator
  delta_star[b] <- (20 / 30) * delta_paired_star +
    (10 / 30) * delta_single_star
}
```


```{r}
ci_percentile <- quantile(delta_star, probs = c(0.025, 0.975))
ci_percentile
```


```{r}
q_delta <- quantile(delta_star, probs = c(0.025, 0.975))
ci_basic <- c(
  2 * delta_hat - q_delta[2],
  2 * delta_hat - q_delta[1])
ci_basic
```


## Part III

```{r}
set.seed(202604)

n <- length(blue)

delta_wrong_star <- numeric(B)

delta_wrong_hat <- mean(blue) - mean(red)

for (b in 1:B) {
  blue_star_wrong <- sample(blue, size = n, replace = TRUE)
  red_star_wrong  <- sample(red,  size = n, replace = TRUE)
  
  delta_wrong_star[b] <- mean(blue_star_wrong) - mean(red_star_wrong)
}

# Percentile CI
ci_wrong_percentile <- quantile(delta_wrong_star, probs = c(0.025, 0.975))

# Basic CI
q_wrong <- quantile(delta_wrong_star, probs = c(0.025, 0.975))

ci_wrong_basic <- c(
  2 * delta_wrong_hat - q_wrong[2],
  2 * delta_wrong_hat - q_wrong[1]
)

ci_wrong_percentile
ci_wrong_basic
```


```{r}
# correct CIs from part (b)
ci_correct_percentile <- c(-5.670833, 12.200833)
ci_correct_basic <- c(-6.06750, 11.80417)

# widths
width_correct_percentile <- diff(ci_correct_percentile)
width_correct_basic <- diff(ci_correct_basic)

width_wrong_percentile <- diff(ci_wrong_percentile)
width_wrong_basic <- diff(ci_wrong_basic)

width_correct_percentile
width_wrong_percentile

width_correct_basic
width_wrong_basic
```



# Problem 3

```{r}
data("Boston")
set.seed(42) 
idx <- sample(nrow(Boston), size = floor(0.8 * nrow(Boston)))

train <- Boston[idx, ]
test <- Boston[-idx, ]

nrow(train)
nrow(test)
```


# Problem 4.1

```{r}
X_train <- model.matrix(medv ~ ., train)[, -1]
y_train <- train$medv

set.seed(42)
cv_fit <- cv.glmnet(
  X_train,
  y_train,
  alpha = 1,
  nfolds = 5
)

cv_df <- data.frame(
  lambda = cv_fit$lambda,
  log_lambda = log(cv_fit$lambda),
  mse = cv_fit$cvm
)


cv_df <- cv_df[order(cv_df$log_lambda), ]

plot(
  cv_df$log_lambda,
  cv_df$mse,
  type = "l",
  lwd = 2,
  xlab = expression(log(lambda)),
  ylab = "Cross-validated MSE",
  main = "5-fold CV Curve for LASSO"
)

points(
  cv_df$log_lambda,
  cv_df$mse,
  pch = 19,
  cex = 0.6
)

abline(v = log(cv_fit$lambda.min), lty = 2)
abline(v = log(cv_fit$lambda.1se), lty = 3)

legend(
  "topleft",
  legend = c(expression(lambda[min]), expression(lambda["1se"])),
  lty = c(2, 3),
  bty = "n"
)

lambda_min <- cv_fit$lambda.min
lambda_1se <- cv_fit$lambda.1se

lambda_min
lambda_1se
```


```{r}
coef_min <- coef(cv_fit, s = "lambda.min")

selected <- coef_min[coef_min[, 1] != 0, , drop = FALSE]
selected_vars <- selected[rownames(selected) != "(Intercept)", , drop = FALSE]

selected_vars

# test MSE
X_test <- model.matrix(medv ~ ., test)[, -1]
y_test <- test$medv

pred_test <- predict(cv_fit, newx = X_test, s = "lambda.min")

test_mse <- mean((y_test - as.numeric(pred_test))^2)
test_mse
```


# Problem 4.2

```{r}
set.seed(42) 
# In order to keep the comparability with problem 3 and 4.1, the seed was set as 42.

B <- 500

n_train <- nrow(train)
n_test <- nrow(test)

pred_mat <- matrix(NA, nrow = n_test, ncol = B)

for (b in 1:B) {
  idx_boot <- sample(1:n_train, size = n_train, replace = TRUE)
  boot_train <- train[idx_boot, ]
  
  X_boot <- model.matrix(medv ~ ., boot_train)[, -1]
  y_boot <- boot_train$medv
  
  cv_boot <- cv.glmnet(
    X_boot,
    y_boot,
    alpha = 1,
    nfolds = 5
  )
  
  lambda_boot <- cv_boot$lambda.min
  
  fit_boot <- glmnet(
    X_boot,
    y_boot,
    alpha = 1,
    lambda = lambda_boot
  )
  
  pred_mat[, b] <- as.numeric(
    predict(fit_boot, newx = X_test)
  )
}

y_smooth <- rowMeans(pred_mat)

mse_smooth <- mean((y_test - y_smooth)^2)

mse_smooth
```

















































































































